spring.application.name=Apartment

server.port=8080

# Supabase PostgreSQL connection (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.titddcblchwxvhyocosx
spring.datasource.password=2452724dacar
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=ApartmentManagementSystemSuperSecretKeyForJwtSigning2026ChangeMeInProd
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173